version: 2
jobs:
  test:
    docker:
      - image: golang:1.12.4-stretch
    working_directory: "/go/src/github.com/ellcrys/elld"
    steps:
      - checkout
      - run:
          name: Install Dep
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            go get github.com/onsi/ginkgo/ginkgo
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install Dependencies
          command: |
            dep ensure -v
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - "vendor"
      - run:
          name: Run tests
          command: |
            ginkgo -v ./...

workflows:
  version: 2
  build:
    jobs:
      - test
